# Generated by Django 4.2.5 on 2023-10-18 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrapSafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='crap_safe')),
                ('is_craped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CrapUnsafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='crap_unsafe')),
                ('is_craped', models.BooleanField(default=False)),
            ],
        ),
    ]
